easy_admin:
    entities:
#        # List the entity class name you want to manage
       BlogPost:
          class: App\Entity\BlogPost
          list:
            actions: [ { name: 'Show' } ]
          show:
            fields:
              - id
              - title
              - published
              - { property: 'comments', template: 'easy_admin/BlogPost/comments.html.twig' }
              - images
       User:
          class: App\Entity\User
          edit:
            fields:
              - username
              - name
              - firstName
              - gender
              - email
              - profilePicture
              - roles
              - enabled
              - birthDate
              - birthPlace
              - work
              - weight
              - height
              - eyeColor
              - hairColor
              - ticketUrl
          new:
            fields:
              - username
              - password
              - name
              - firstName
              - gender
              - email
              - profilePicture
              - roles
              - enabled
              - birthDate
              - birthPlace
              - work
              - weight
              - height
              - eyeColor
              - hairColor
              - ticketUrl
          controller: App\Controller\UserAdminController
       Lieu:
          class: App\Entity\Lieu
       Image:
          class: App\Entity\Image
          list:
            fields:
              - id
              - { property : 'url', type: 'image', label: 'Image' }
          form:
            fields:
              - { property : 'file', type: 'Vich\UploaderBundle\Form\Type\VichFileType' }
       Comment:
          class: App\Entity\Comment
       Articles:
          class: App\Entity\Articles
          list:
              actions: [ { name: 'Show' } ]
          edit:
            fields:
              - title
              - intro
              - coverImage
              - timeToRead
          new:
            fields:
              - title
              - intro
              - coverImage
              - timeToRead
          show:
            fields:
              - title
              - intro
              - coverImage
              - timeToRead
              - sections
       Section:
         class: App\Entity\Section
       TimeEvent:
         class: App\Entity\TimeEvent
         edit:
           - title
           - text
           - picture
           - buttonLabel
           - buttonUrl
         new:
           - title
           - text
           - picture
           - buttonLabel
           - buttonUrl
       Calendar:
         class: App\Entity\Calendar


